### PR TITLE
Navigation enhancements

### PR DESCRIPTION
**Pull request by Optiroc**
New cleaned up PR with the navigation enhancements. 

However! I didn't find a sane way to split these up as two feature branches and PR separately, since I build upon changes in the same functions. Here the features are more clearly added in two commits at least.

### CODE REVIEW

**Comment by MagerValp** [comment]
Much obliged! I've got FS-UAE up and running again, slowly figuring out how my dev environment was set up...

**Comment by MagerValp** [comment]
Looks good, merging.

**Comment by Optiroc** [comment]
Cool! Not super proud about `agsmenupos.read()`, but with no proper language/dos api reference that's how it went down... :)

Is there a full reference online somewhere? The best documentation I found was this [beginners guide](http://cshandley.co.uk/JasonHulance/beginner_toc.html). A good languange reference, but it doesn't cover the AmigaDOS modules.

**Comment by MagerValp** [comment]
My surviving bookmarks:

http://amigadev.elowar.com/read/ADCD_2.1/
http://amigadev.elowar.com/read/ADCD_2.1/Includes_and_Autodocs_3._guide/node0000.html
http://cshandley.co.uk/amigae/

**Pull request merged**
