### PR TITLE
Added slideshow support for screenshots.

### PR DESCRIPTION
**Pull request by Stat-Mat**
Also fixed screen corruption issue when using screenshots with varying resolutions.

### CODE REVIEW

**Comment by Optiroc** [comment]
Thanks, looks good! I'll try to find the time to test this out and merge today.

**Comment by Optiroc** [comment]
Sorry about the delay, but now I've finally compiled and tested a bit!

I found two little issues. Maybe you have a hunch on why they happen, so I'll hold off a bit with debugging them myself.

- When returning to the launcher (load launcher -> load game and quit -> launcher reloads) there are palette glitches. Always at the start of fade-in, but sometimes the glitchy palette sticks until selecting a new title and a new image is loaded.
- By chance one of the images on my current test drive was [this ugly face](https://github.com/Optiroc/AGSImager/blob/master/data/img/game--dangerfreak--dangerfreak.iff) from "Danger Freak". For some reason there is a white line rendered along the right and bottom edges.

**Comment by Stat-Mat** [comment]
No problem! Many thanks for testing and catching those issues. I think I know what is causing both of them, so I will take a look and see what I can do to address them.

**Comment by Stat-Mat** [comment]
Okay, so those two issues have now been resolved.

The first was being caused by the area not being erased behind the first image loaded, as the last width and height properties had not been initialised.

The second was being caused by not deducting one from the calculated lower right corner coordinates. This was inadvertently removed from the original code when updating it to support erasure of the area behind any previously displayed image. This was happening for all images, but was appearing as white lines with the provided example image for Danger Freak due to the fact that the image has 7 bitplanes (depth) instead of 8 (i.e. having a 128 colour palette instead of 256).

**Comment by Optiroc** [comment]
Good stuff!

**Comment by CommodoreOS** [comment]
Iff image files from AGS 1.0 do not display properly in AGS2, the colours on the images are like a negative..?

**Pull request merged**
